#!/usr/bin/env python3
"""
generate_news_rss.py — Wave WW Round 2 SEO: RSS 2.0 feed for /news

Outputs:
  - /feed.xml (English, default)
  - /feed-ja.xml
  - /feed-pt.xml

Items: featured techniques (3 per locale, rotated weekly) + recent milestones.
Helps:
  - Power users subscribe via RSS readers
  - Crawlers (Bing, Mojeek, etc.) discover fresh content
  - Adds RSS link to <head> via robots.txt and HTML for autodiscovery

Cron: regenerated by news_weekly.yml workflow.
"""
from __future__ import annotations
import datetime as dt
import html as html_mod
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "data" / "news_feed.yml"

LANG_META = {
    "en": {
        "title": "BJJ App Wiki — BJJ Weekly",
        "desc": "Featured BJJ techniques, real tournament calendars, and weekly wiki updates.",
        "lang": "en-US",
    },
    "ja": {
        "title": "BJJ App Wiki — BJJ ウィークリー",
        "desc": "今週の注目 BJJ テクニック、JBJJF / IBJJF / ADCC など実在の大会、Wiki 更新。",
        "lang": "ja-JP",
    },
    "pt": {
        "title": "BJJ App Wiki — BJJ Semanal",
        "desc": "Técnicas em destaque, calendários de torneios (CBJJ, IBJJF, ADCC) e atualizações do wiki.",
        "lang": "pt-BR",
    },
}

OUTPUT_BY_LANG = {
    "en": "feed.xml",      # default English
    "ja": "feed-ja.xml",
    "pt": "feed-pt.xml",
}


def load_yaml() -> dict:
    import yaml
    return yaml.safe_load(DATA_FILE.read_text(encoding="utf-8"))


def rfc822(d: dt.date) -> str:
    """RFC-822 formatted date for RSS."""
    return d.strftime("%a, %d %b %Y 09:00:00 +0900")


def build_rss(lang: str, data: dict, today: dt.date) -> str:
    meta = LANG_META[lang]
    items = []

    # Featured techniques (3 per week, rotated)
    pool = data.get("featured_techniques") or []
    week_idx = today.isocalendar()[1]
    n = 3
    for i in range(n):
        if not pool:
            break
        item = pool[(week_idx * n + i) % len(pool)]
        title = item.get(lang, item.get("en", item["slug"]))
        slug = item["slug"]
        url = f"https://wiki.bjj-app.net/{lang}/{slug}.html"
        items.append({
            "title": title,
            "url": url,
            "desc": title,
            "pubDate": today,
        })

    # Recent milestones (last 5)
    for ms in (data.get("milestones") or [])[:5]:
        msg = ms.get(lang, ms.get("en", ""))
        date_str = str(ms.get("date", ""))
        try:
            d = dt.date.fromisoformat(date_str)
        except Exception:
            d = today
        items.append({
            "title": msg[:80],
            "url": f"https://wiki.bjj-app.net/{lang}/news.html",
            "desc": msg,
            "pubDate": d,
        })

    feed_url = f"https://wiki.bjj-app.net/{OUTPUT_BY_LANG[lang]}"
    site_url = f"https://wiki.bjj-app.net/{lang}/news.html"

    items_xml = ""
    for it in items:
        items_xml += f"""    <item>
      <title>{html_mod.escape(it['title'])}</title>
      <link>{html_mod.escape(it['url'])}</link>
      <guid isPermaLink="true">{html_mod.escape(it['url'])}</guid>
      <description>{html_mod.escape(it['desc'])}</description>
      <pubDate>{rfc822(it['pubDate'])}</pubDate>
    </item>\n"""

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>{html_mod.escape(meta['title'])}</title>
    <link>{site_url}</link>
    <description>{html_mod.escape(meta['desc'])}</description>
    <language>{meta['lang']}</language>
    <lastBuildDate>{rfc822(today)}</lastBuildDate>
    <atom:link href="{feed_url}" rel="self" type="application/rss+xml" />
{items_xml}  </channel>
</rss>
"""


def main() -> int:
    today = dt.date.today()
    data = load_yaml()
    for lang, out_name in OUTPUT_BY_LANG.items():
        rss = build_rss(lang, data, today)
        out_path = REPO_ROOT / out_name
        out_path.write_text(rss, encoding="utf-8")
        print(f"  Generated {out_name} ({len(rss):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
